name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # Windows build is not yet working due to issues with the checked-in z3.exe
        os: [ubuntu-latest]
        shard: [1, 2, 3, 4, 5]
      fail-fast: false
    steps:
    - name: Setup Nuget
      uses: nuget/setup-nuget@v1
    - name: Manually sync certs
      run: cert-sync /etc/ssl/certs/ca-certificates.crt
    - name: Checkout Dafny
      uses: actions/checkout@v2
      with:
        submodules: recursive
        path: dafny
    - name: Get Z3
      if: matrix.os != 'windows-latest'
      run: |
        wget https://github.com/Z3Prover/z3/releases/download/z3-4.8.4/z3-4.8.4.d6df51951f4c-x64-ubuntu-14.04.zip
        unzip z3*.zip && rm *.zip
        cp -r z3* dafny/Binaries/z3
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1.6.0
      with:
        dotnet-version: '3.1.x' # SDK Version to use; x will use the latest version of the 3.1 channel
    - name: Build Dafny
      run: dotnet build dafny/Source/Dafny.sln
    - uses: actions/setup-python@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build and Copy DafnyRuntime.jar with Gradle
      run: dafny/Source/DafnyRuntime/DafnyRuntimeJava/gradlew -p dafny/Source/DafnyRuntime/DafnyRuntimeJava copyJarToBinaries
    - name: Upgrade outdated pip
      run: python -m pip install --upgrade pip
    - name: Install lit
      run: pip install lit OutputCheck pyyaml
    - uses: actions/setup-node@v1
    - run: npm install bignumber.js
    - name: Run lit tests
      run: lit --time-tests -v --num-shards=5 --run-shard=${{ matrix.shard }} dafny/Test
